/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.univates.apresentacao;

import br.univates.negocio.Usuario;
import br.univates.persistencia.DaoFactory;
import br.univates.raiz.persistence.IDao;
import br.univates.raiz.persistence.InvalidKeyException;
import br.univates.raiz.persistence.KeyViolationException;
import br.univates.raiz.persistence.NotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author luis.dutra
 */
public class TelaUsuarioUI extends javax.swing.JFrame {

    private Usuario usuarioCurrent;
    private Usuario usuarioOld;
    private boolean novo;
    
    /**
     * Creates new form TelaUsuarioUI
     */
    public TelaUsuarioUI() {
        initComponents();
        
        ArrayList<Usuario> usuarios = DaoFactory.criarUsuarioDao().readAll();
        
        this.tbConsultaUsuarios.setModel( new TableModelUsuario(usuarios));
        this.novo = false;
        
        this.btnSalvarEditar.setEnabled(false);
        this.btnSalvarNovo.setEnabled(false);
        
        this.btnCancelarEditar.setEnabled(false);
        this.btnCancelarNovo.setEnabled(false);
        
        this.btnVoltar.setEnabled(true);
        
        this.painelAbas.setSelectedIndex(0);
        
        this.setLocationRelativeTo(null);
    }
    
    public void setUsuario(Usuario usuario) {
    
        this.usuarioCurrent = usuario;
        
        this.tfIDUsuario.setText("");
        this.tfNomeUsuario.setText(usuario.getName());
        this.tfSenhaUsuario.setText(usuario.getHashCode());
        this.tfUserUsuario.setText(usuario.getLogName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbConsultaUsuarios = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        painelAbas = new javax.swing.JTabbedPane();
        tabInicial = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabNovo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNomeUsuario = new br.univates.raiz.JTextFieldCustomized();
        tfUserUsuario = new br.univates.raiz.JTextFieldCustomized();
        tfIDUsuario = new br.univates.raiz.JIntegerField();
        tfSenhaUsuario = new br.univates.raiz.JTextFieldCustomized();
        btnCancelarNovo = new javax.swing.JButton();
        btnSalvarNovo = new javax.swing.JButton();
        tabEditar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfNovoNomeUsuario = new br.univates.raiz.JTextFieldCustomized();
        btnSalvarEditar = new javax.swing.JButton();
        btnCancelarEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbConsultaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbConsultaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbConsultaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbConsultaUsuarios);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        painelAbas.setToolTipText("");

        jLabel1.setText("Tela de Usuários");

        javax.swing.GroupLayout tabInicialLayout = new javax.swing.GroupLayout(tabInicial);
        tabInicial.setLayout(tabInicialLayout);
        tabInicialLayout.setHorizontalGroup(
            tabInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabInicialLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        tabInicialLayout.setVerticalGroup(
            tabInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabInicialLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        painelAbas.addTab("inicial", tabInicial);

        jLabel2.setText("ID: ");

        jLabel3.setText("Nome: ");

        jLabel4.setText("User: ");

        jLabel5.setText("Senha: ");

        tfNomeUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNomeUsuarioFocusLost(evt);
            }
        });

        tfUserUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUserUsuarioFocusLost(evt);
            }
        });

        tfIDUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfIDUsuarioFocusLost(evt);
            }
        });

        tfSenhaUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSenhaUsuarioFocusLost(evt);
            }
        });

        btnCancelarNovo.setText("Cancelar");
        btnCancelarNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarNovoActionPerformed(evt);
            }
        });

        btnSalvarNovo.setText("Salvar");
        btnSalvarNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabNovoLayout = new javax.swing.GroupLayout(tabNovo);
        tabNovo.setLayout(tabNovoLayout);
        tabNovoLayout.setHorizontalGroup(
            tabNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabNovoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabNovoLayout.createSequentialGroup()
                        .addGroup(tabNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(tabNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfUserUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfIDUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)))
                    .addGroup(tabNovoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabNovoLayout.createSequentialGroup()
                                .addComponent(btnCancelarNovo)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvarNovo))
                            .addComponent(tfSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        tabNovoLayout.setVerticalGroup(
            tabNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabNovoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfUserUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarNovo)
                    .addComponent(btnSalvarNovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelAbas.addTab("novo", tabNovo);

        jLabel6.setText("Nome: ");

        tfNovoNomeUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNovoNomeUsuarioFocusLost(evt);
            }
        });

        btnSalvarEditar.setText("Salvar");
        btnSalvarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEditarActionPerformed(evt);
            }
        });

        btnCancelarEditar.setText("Cancelar");
        btnCancelarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabEditarLayout = new javax.swing.GroupLayout(tabEditar);
        tabEditar.setLayout(tabEditarLayout);
        tabEditarLayout.setHorizontalGroup(
            tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEditarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabEditarLayout.createSequentialGroup()
                        .addComponent(btnCancelarEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvarEditar))
                    .addGroup(tabEditarLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tfNovoNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        tabEditarLayout.setVerticalGroup(
            tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEditarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfNovoNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarEditar)
                    .addComponent(btnCancelarEditar))
                .addContainerGap())
        );

        painelAbas.addTab("editar", tabEditar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addContainerGap())
            .addComponent(painelAbas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 214, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnVoltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbConsultaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbConsultaUsuariosMouseClicked
        int linhaSelecionada  = this.tbConsultaUsuarios.getSelectedRow();
        
        TableModelUsuario model = (TableModelUsuario)this.tbConsultaUsuarios.getModel();
        Usuario usuario = model.getUsuarios().get( linhaSelecionada );
        
        this.setUsuario(usuario);
    }//GEN-LAST:event_tbConsultaUsuariosMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.painelAbas.setSelectedIndex(1);
        
        this.btnSalvarNovo.setEnabled(true);
        this.btnCancelarNovo.setEnabled(true);
        this.btnVoltar.setEnabled(true);
        
        this.tfIDUsuario.setEditable(true);
        this.tfNomeUsuario.setEditable(true);
        this.tfUserUsuario.setEditable(true);
        this.tfSenhaUsuario.setEditable(true);
        
        this.novo = true;
        
        if (usuarioCurrent != null) {
            this.usuarioOld = usuarioCurrent.clone();
        }
        
        this.setUsuario(new Usuario());
        this.tfIDUsuario.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.painelAbas.setSelectedIndex(2);
        
        if (usuarioCurrent != null) {
            this.usuarioOld = usuarioCurrent.clone();
            this.btnSalvarEditar.setEnabled(true);
            this.btnCancelarEditar.setEnabled(true);
            this.btnVoltar.setEnabled(true);
            
            this.novo = false;
            this.tfNovoNomeUsuario.setEditable(true);
            this.tfNovoNomeUsuario.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um usuário na tabela");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (usuarioCurrent != null)
        {
            try
            {
                int x = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir?", 
                                                            "Confirmação", 
                                                            JOptionPane.YES_NO_OPTION);
                
                if (x == 0)
                {
                    DaoFactory.criarUsuarioDao().delete( usuarioCurrent.getIdUser() );

                    TableModelUsuario model = (TableModelUsuario)this.tbConsultaUsuarios.getModel();
                    model.getUsuarios().remove(usuarioCurrent);

                    this.tbConsultaUsuarios.revalidate();
                    this.tbConsultaUsuarios.repaint();
                    this.tfIDUsuario.setText( "" );
                    this.tfNomeUsuario.setText( "" );
                    this.tfSenhaUsuario.setText( "" );
                    this.tfUserUsuario.setText( "" );
                    this.tfNovoNomeUsuario.setText( "" );
                    this.usuarioCurrent = null;
                }
            } 
            catch (NotFoundException ex)
            {
                JOptionPane.showMessageDialog(this, "Este usuário não pode ser deletado");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Selecione um usuário na tabela");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void tfIDUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIDUsuarioFocusLost
        this.usuarioCurrent.setIdUser(this.tfIDUsuario.getInteger());
    }//GEN-LAST:event_tfIDUsuarioFocusLost

    private void tfNomeUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNomeUsuarioFocusLost
        this.usuarioCurrent.setNome(this.tfNomeUsuario.getText());
    }//GEN-LAST:event_tfNomeUsuarioFocusLost

    private void tfUserUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserUsuarioFocusLost
        this.usuarioCurrent.setUser(this.tfUserUsuario.getText());
    }//GEN-LAST:event_tfUserUsuarioFocusLost

    private void tfSenhaUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSenhaUsuarioFocusLost
        this.usuarioCurrent.setHashCode(this.tfSenhaUsuario.getText());
    }//GEN-LAST:event_tfSenhaUsuarioFocusLost

    private void tfNovoNomeUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNovoNomeUsuarioFocusLost
        this.usuarioCurrent.setNome(this.tfNovoNomeUsuario.getText());
    }//GEN-LAST:event_tfNovoNomeUsuarioFocusLost

    private void btnCancelarNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarNovoActionPerformed
        if (usuarioOld != null)
        {
            this.usuarioCurrent.setIdUser(this.usuarioOld.getIdUser() );
            this.usuarioCurrent.setNome( this.usuarioOld.getName() );
            this.usuarioCurrent.setUser(this.usuarioOld.getLogName() );
            this.usuarioCurrent.setHashCode(this.usuarioOld.getHashCode() );
            this.tfIDUsuario.setText( this.usuarioOld.getIdUser()+"" );
            this.tfNomeUsuario.setText( this.usuarioOld.getName());
            this.tfUserUsuario.setText( this.usuarioOld.getLogName());
            this.tfSenhaUsuario.setText( this.usuarioOld.getHashCode());
        }
        
        this.tbConsultaUsuarios.revalidate();
        this.tbConsultaUsuarios.repaint();
        
        this.tfIDUsuario.setEditable(false);
        this.tfNomeUsuario.setEditable(false);
        this.tfUserUsuario.setEditable(false);
        this.tfSenhaUsuario.setEditable(false);

        this.btnSalvarNovo.setEnabled(false);
        this.btnCancelarNovo.setEnabled(false);
        this.btnVoltar.setEnabled(true);
    }//GEN-LAST:event_btnCancelarNovoActionPerformed

    private void btnCancelarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEditarActionPerformed
        if (usuarioOld != null)
        {
            this.usuarioCurrent.setIdUser(this.usuarioOld.getIdUser() );
            this.usuarioCurrent.setNome( this.usuarioOld.getName() );
            this.usuarioCurrent.setUser(this.usuarioOld.getLogName() );
            this.usuarioCurrent.setHashCode(this.usuarioOld.getHashCode() );
            this.tfNovoNomeUsuario.setText( this.usuarioOld.getName() );
        }
        
        this.tbConsultaUsuarios.revalidate();
        this.tbConsultaUsuarios.repaint();
        
        this.tfNovoNomeUsuario.setEditable(false);

        this.btnSalvarEditar.setEnabled(false);
        this.btnCancelarEditar.setEnabled(false);
        this.btnVoltar.setEnabled(true);
    }//GEN-LAST:event_btnCancelarEditarActionPerformed

    private void btnSalvarNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarNovoActionPerformed
        IDao<Usuario,Integer> dao = DaoFactory.criarUsuarioDao();

        try
        {
            if (novo)
            {
                dao.create(usuarioCurrent);

                TableModelUsuario model = (TableModelUsuario)this.tbConsultaUsuarios.getModel();
                model.getUsuarios().add(usuarioCurrent);
            }

            this.tbConsultaUsuarios.revalidate();
            this.tbConsultaUsuarios.repaint();

            this.tfIDUsuario.setEditable(false);
            this.tfNomeUsuario.setEditable(false);
            this.tfUserUsuario.setEditable(false);
            this.tfSenhaUsuario.setEditable(false);

            this.btnSalvarNovo.setEnabled(false);
            this.btnCancelarNovo.setEnabled(false);
            this.btnVoltar.setEnabled(true);
        }
        catch (KeyViolationException | InvalidKeyException ex) 
        {
            JOptionPane.showMessageDialog(this, ex.getMessage() );
        }
    }//GEN-LAST:event_btnSalvarNovoActionPerformed

    private void btnSalvarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEditarActionPerformed
        IDao<Usuario,Integer> dao = DaoFactory.criarUsuarioDao();

        try
        {
            if (!novo)
            {
                dao.update(usuarioCurrent);
            }

            this.tbConsultaUsuarios.revalidate();
            this.tbConsultaUsuarios.repaint();

            this.tfNovoNomeUsuario.setEditable(false);

            this.btnSalvarEditar.setEnabled(false);
            this.btnCancelarEditar.setEnabled(false);
            this.btnVoltar.setEnabled(true);
            
        } catch (NotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage() );
        }
    }//GEN-LAST:event_btnSalvarEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarEditar;
    private javax.swing.JButton btnCancelarNovo;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvarEditar;
    private javax.swing.JButton btnSalvarNovo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane painelAbas;
    private javax.swing.JPanel tabEditar;
    private javax.swing.JPanel tabInicial;
    private javax.swing.JPanel tabNovo;
    private javax.swing.JTable tbConsultaUsuarios;
    private br.univates.raiz.JIntegerField tfIDUsuario;
    private br.univates.raiz.JTextFieldCustomized tfNomeUsuario;
    private br.univates.raiz.JTextFieldCustomized tfNovoNomeUsuario;
    private br.univates.raiz.JTextFieldCustomized tfSenhaUsuario;
    private br.univates.raiz.JTextFieldCustomized tfUserUsuario;
    // End of variables declaration//GEN-END:variables
}
