/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.univates.apresentacao;

import br.univates.menurapido.Sys;
import br.univates.negocio.Usuario;
import br.univates.persistencia.DaoFactory;
import br.univates.raiz.auth.Authenticator;
import br.univates.raiz.db.DataBaseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author luis.dutra
 */
public class TelaMenuUI extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public TelaMenuUI() {
        
        initComponents();
        
        this.btnTelaCategoria.setEnabled(false);
        this.btnTelaMesas.setEnabled(false);
        this.btnTelaProdutos.setEnabled(false);
        this.btnTelaStatusAtendimento.setEnabled(false);
        this.btnTelaTipoPagamento.setEnabled(false);
        this.btnTelaUsuario.setEnabled(false);
        this.btnTelaPedidos.setEnabled(false);
        this.btnTelaPagamento.setEnabled(false);
        this.btnTelaStatusPedidos.setEnabled(false);
        
        this.setLocationRelativeTo(null);
    }

    private Usuario userVerifier()
    {
        ArrayList<Usuario> users = DaoFactory.criarUsuarioDao().readAll();
        Authenticator auth = new Authenticator( users );
        if (auth.showDialog(true))
        {
            return (Usuario)auth.getLoggedUser();
        }
        return null;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        lbUsuarioConectado = new javax.swing.JLabel();
        btnTelaPedidos = new javax.swing.JButton();
        btnTelaPagamento = new javax.swing.JButton();
        btnTelaStatusPedidos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnSistema = new javax.swing.JMenu();
        btnLoggin = new javax.swing.JMenuItem();
        btnTelaUsuario = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        btnTelaMesas = new javax.swing.JMenuItem();
        btnTelaCategoria = new javax.swing.JMenuItem();
        btnTelaTipoPagamento = new javax.swing.JMenuItem();
        btnTelaStatusAtendimento = new javax.swing.JMenuItem();
        btnTelaProdutos = new javax.swing.JMenuItem();
        btnSair = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Usuário Conectado: ");

        btnTelaPedidos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnTelaPedidos.setText("Pedidos");
        btnTelaPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaPedidosActionPerformed(evt);
            }
        });

        btnTelaPagamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTelaPagamento.setText("Pagamento");
        btnTelaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaPagamentoActionPerformed(evt);
            }
        });

        btnTelaStatusPedidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTelaStatusPedidos.setText("Status dos Pedidos");
        btnTelaStatusPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaStatusPedidosActionPerformed(evt);
            }
        });

        btnSistema.setText("Sistema");

        btnLoggin.setText("Log in / off");
        btnLoggin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogginActionPerformed(evt);
            }
        });
        btnSistema.add(btnLoggin);

        btnTelaUsuario.setText("Usuários");
        btnTelaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaUsuarioActionPerformed(evt);
            }
        });
        btnSistema.add(btnTelaUsuario);

        jMenu1.setText("Cadastros secundários");

        btnTelaMesas.setText("Mesas");
        btnTelaMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaMesasActionPerformed(evt);
            }
        });
        jMenu1.add(btnTelaMesas);

        btnTelaCategoria.setText("Categoria de Produtos");
        btnTelaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(btnTelaCategoria);

        btnTelaTipoPagamento.setText("Tipo de Pagamentos");
        btnTelaTipoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaTipoPagamentoActionPerformed(evt);
            }
        });
        jMenu1.add(btnTelaTipoPagamento);

        btnTelaStatusAtendimento.setText("Status de Atendimento");
        btnTelaStatusAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaStatusAtendimentoActionPerformed(evt);
            }
        });
        jMenu1.add(btnTelaStatusAtendimento);

        btnTelaProdutos.setText("Produtos");
        btnTelaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(btnTelaProdutos);

        btnSistema.add(jMenu1);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        btnSistema.add(btnSair);

        jMenuBar1.add(btnSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUsuarioConectado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnTelaPedidos)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnTelaPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnTelaStatusPedidos)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lbUsuarioConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnTelaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTelaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTelaStatusPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Sys.getInstance().getDB().closeConnection();
        } catch (DataBaseException ex) {
            JOptionPane.showMessageDialog(null, 
                    "Erro fatal ao encerrar a conexão com o banco de dados",
                    "Conexão com o banco de dados", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        try {
            Sys.getInstance().getDB().closeConnection();
        } catch (DataBaseException ex) {
            JOptionPane.showMessageDialog(null, 
                    "Erro fatal ao encerrar a conexão com o banco de dados",
                    "Conexão com o banco de dados", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnLogginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogginActionPerformed
        
        Usuario aux = (Usuario)Sys.getInstance().getUser();
        Sys.getInstance().setUser(null);
        
        Usuario u = userVerifier();
        if (u != null)
        {
            Sys.getInstance().setUser(u);
            this.lbUsuarioConectado.setText(u.getName());
            
            this.btnTelaCategoria.setEnabled(true);
            this.btnTelaMesas.setEnabled(true);
            this.btnTelaProdutos.setEnabled(true);
            this.btnTelaStatusAtendimento.setEnabled(true);
            this.btnTelaTipoPagamento.setEnabled(true);
            this.btnTelaUsuario.setEnabled(true);
            this.btnTelaPedidos.setEnabled(true);
            this.btnTelaPagamento.setEnabled(true);
            this.btnTelaStatusPedidos.setEnabled(true);
        }
        else
        {
            Sys.getInstance().setUser(aux);
        }
    }//GEN-LAST:event_btnLogginActionPerformed

    private void btnTelaPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaPedidosActionPerformed
        TelaPedidoUI tela = new TelaPedidoUI(this);
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTelaPedidosActionPerformed

    private void btnTelaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaUsuarioActionPerformed
        TelaUsuarioUI tela = new TelaUsuarioUI(this);
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTelaUsuarioActionPerformed

    private void btnTelaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaPagamentoActionPerformed
        TelaPagamentoUI tela = new TelaPagamentoUI(this);
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTelaPagamentoActionPerformed

    private void btnTelaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaCategoriaActionPerformed
        TelaCategoriaUI tela = new TelaCategoriaUI(this);
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTelaCategoriaActionPerformed

    private void btnTelaMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaMesasActionPerformed
        TelaMesaUI tela = new TelaMesaUI(this);
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTelaMesasActionPerformed

    private void btnTelaTipoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaTipoPagamentoActionPerformed
        TelaTipoUI tela = new TelaTipoUI(this);
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTelaTipoPagamentoActionPerformed

    private void btnTelaStatusAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaStatusAtendimentoActionPerformed
        TelaStatusUI tela = new TelaStatusUI(this);
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTelaStatusAtendimentoActionPerformed

    private void btnTelaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaProdutosActionPerformed
        TelaProdutoUI tela = new TelaProdutoUI(this);
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTelaProdutosActionPerformed

    private void btnTelaStatusPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaStatusPedidosActionPerformed
        TelaStatusPedidosUI tela = new TelaStatusPedidosUI(this);
        tela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTelaStatusPedidosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnLoggin;
    private javax.swing.JMenuItem btnSair;
    private javax.swing.JMenu btnSistema;
    private javax.swing.JMenuItem btnTelaCategoria;
    private javax.swing.JMenuItem btnTelaMesas;
    private javax.swing.JButton btnTelaPagamento;
    private javax.swing.JButton btnTelaPedidos;
    private javax.swing.JMenuItem btnTelaProdutos;
    private javax.swing.JMenuItem btnTelaStatusAtendimento;
    private javax.swing.JButton btnTelaStatusPedidos;
    private javax.swing.JMenuItem btnTelaTipoPagamento;
    private javax.swing.JMenuItem btnTelaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbUsuarioConectado;
    // End of variables declaration//GEN-END:variables
}
